from dataset import VideoSumDataset
from create_prompt import *
from utils import *
import os
import argparse
from openai import OpenAI
import numpy as np
import json
from typing import Any, Union
from pathlib import Path

PathLike = Union[str, Path]

def assign_framescore(allcaptions, scores): 
    """
    Assign frame-level scores based on generated caption scores.

    Args:
        allcaptions (list of str): Captions to be scored (e.g., full video).
        scores (dict): Caption-to-score mapping generated by the LLM.

    Returns:
        np.ndarray: Frame-level score array.
    """
    frame_scores = []
    for line in allcaptions:
        if line in scores:
            frame_scores.append(scores[line])
        else:
            escaped_line = line.replace('"', '\"')
            if escaped_line in scores:
                frame_scores.append(scores[escaped_line])
            else:
                frame_scores.append(frame_scores[-1] if frame_scores else 0) 
    return np.array(frame_scores)
    
    
def adjust_framescore(original_length, reduced_scores, ratio):
    """
    Adjust frame-level scores by upsampling reduced caption-level scores.

    Args:
        original_length (int): Total number of original frames or captions.
        reduced_scores (np.ndarray): Scores corresponding to reduced captions.
        ratio (int): Reduction ratio used during downsampling.

    Returns:
        np.ndarray: Adjusted score array with length equal to `original_length`.
    """
    expanded_scores = []
    for i in range(original_length):
        expanded_scores.append(reduced_scores[i//ratio])
    return np.array(expanded_scores)

def main(args):
    set_random_seed(args.seed)
    yaml_path = f"../datasets/{args.dataset}/ZS_videos.yml"
    TOKEN = load('./settings.json')['token']
    client = OpenAI(api_key=TOKEN)
    LLM_model = "gpt-4o"
    keys_info = load_yaml(yaml_path) 
    test_keys = keys_info[0]['test_keys']
    test_video_dataset = VideoSumDataset(test_keys, args.dataset) 
    video_fscore_dict = {}

    for i in range(len(test_keys)):
        video_fscore = []
        ratio = 1
        if args.dataset == "TVSum":
            # For videos where the full captions do not fit in the LLM context window, we apply downsampling to reduce the input length.
            downsample_indices = {5, 13, 20, 24, 37}
            if i in downsample_indices:
                ratio = 2
        video_name, video_file, change_points, n_frames, n_frame_per_seg, picks, user_summary, caption_path, user_score, original_user_score, caption_lines  = test_video_dataset[i]
        print(video_name)
        
        if args.dataset == "TVSum":
            annonum = 20
            title, genre, query = get_metadata(args, video_name)
                
        for annoindex in range(annonum):
            exampled_prompt = create_training_data(args, annoindex)
            original_caption_str = '\n'.join(caption_lines) 
            format = convert2dict(caption_path, ratio)
            pseudo = pseudo_label(caption_path, ratio) 
            original_captions, reduced_captions, original_caption_str, pseudo = process_captions_scores(caption_path, ratio) 
            prompt = exampled_prompt.replace('[FORMAT]',format).replace('[PSUEDO]',pseudo).replace('[TEST TITLE]',title).replace('[TEST CAPTIONS]', original_caption_str)
            
            response = client.chat.completions.create(
            model=LLM_model,
            response_format={ "type": "json_object" },
            messages=[
                {"role": "system", "content": "You are an expert in text analysis and summarization, specializing in understanding the subtleties of human-generated content."},
                {"role": "user", "content": prompt},
            ],
            temperature=0,
            )
            output_dir = f"../datasets/{args.dataset}/videos/{video_name}/ZS-VSUM"
            if not os.path.exists(output_dir):
                os.mkdir(output_dir)
                    
            output_file = os.path.join(output_dir,f"annotator_{annoindex}.json")
            json_string = response.choices[0].message.content
            scores = json.loads(json_string)
            framescores = assign_framescore(reduced_captions,scores) 
            framescores = adjust_framescore(len(original_captions), framescores, ratio) 

            fscore = calc_fscore(args,framescores,change_points,n_frames,n_frame_per_seg,picks,user_summary,annoindex) 
            np.save(os.path.join(output_dir,f"anno_{annoindex}_{fscore}.npy"), framescores)
            with open(output_file, 'w') as f:
                json.dump(scores, f,indent=4)
            print(fscore)
            video_fscore.append(fscore)
        video_fscore_dict[video_name] = video_fscore
            
    avg_video_fscore_dict = {
        video_name: np.mean(annotator_fscores)
        for video_name, annotator_fscores in video_fscore_dict.items()
    }
    dataset_fscore = np.mean([score for scores in video_fscore_dict.values() for score in scores])

    result_dir = f"../datasets/{args.dataset}/results/ZS-VSUM"
    os.makedirs(result_dir, exist_ok=True)

    result_json = {
        "video_average_fscores": avg_video_fscore_dict,
        "dataset_fscore": dataset_fscore
    }

    with open(os.path.join(result_dir, "fscore.json"), 'w', encoding='utf-8') as f:
        json.dump(result_json, f, indent=4)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--dataset', type=str)
    parser.add_argument('--seed', type=int, default=42)
    args = parser.parse_args()
    
    main(args)
    